- name: Instalando Softwares via APT
  yum:
    name: '{{ item }}'
    install_recommends: yes
    state: present
    update_cache: yes
  loop:
      - vim
      - htop
      - curl
      - wget
      - git
      - python3-pip
      - ansible
      - ansible-lint
      - ssh
- name: Install Apache 2.4 Php 7.2 
  hosts: localhost 
  gather_facts: false 
  become: true 
  tasks:
    - name: install module php 7.2
      command: yum install php72    
    - name: install module apache
      command: yum install httpd    