- name: Install Apache 2.4 Php 7.2 
  hosts: localhost 
  gather_facts: false 
  become: true 
  tasks:
    - name: install module php 7.2
      command: yum install php72    
    - name: install module apache
      command: yum install httpd    
